collections:
  sensibilisations:
    relative_directory: "sensibilisations"
    output: true
    permalink: /services/sensibilisation/:path.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      css: "markdown.css"
      image: "/assets/img/simbios-black.svg"
  - scope:
      path: ""
    values:
      layout: "page"
      css: "markdown.css"
      description: "Pour réduire l'impact environnemental du numérique"
      image: "/assets/img/simbios-black.svg"
sass:
  style: compressed
  
domain: simbios.fr
url: https://simbios.fr
baseurl:

title: Simbios
description: "Aide les entreprises et les particuliers à réduire l'empreinte environnementale de leurs activités numériques."
url: https://simbios.fr
author: 
  twitter: geeyom
  picture: /assets/img/guillaumewolf.webp
logo: /assets/img/simbios-black.svg
social:
  name: Guillaume Wolf
  links:
    - https://www.linkedin.com/in/guillaumewolf
    - https://twitter.com/geeyom
    - https://github.com/guillaumew
locale: 'fr_FR'

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier

paginate: 5
paginate_path: "/blog/page:num/"

jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true